exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

## If you want to automatically "modernize" your Python code:
# - repo: https://github.com/asottile/pyupgrade
#   rev: v3.7.0
#   hooks:
#   - id: pyupgrade
#     args: ['--py37-plus']

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/PyCQA/autoflake
#   rev: v2.1.1
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: latest
  hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [build chore ci docs feat fix perf refactor revert style test]

- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
  - id: isort
  - args: [--settings-file, ./pyproject.toml]

- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/docformatter
  rev: latest
  hooks:
  - id: docformatter
    additional_dependencies: [tomli]
    args: [--in-place, --config, ./pyproject.toml]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.0
  hooks:
  - id: ruff

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    args: [--config, ./pyproject.toml]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
  hooks:
  - id: mypy
    additional_dependencies: [types-python-dateutil]
    args: [--config-file, ./pyproject.toml]
- repo: https://github.com/myint/eradicate
  rev: '2.2.0'
  hooks:
  - id: eradicate
    args: []
- repo: https://github.com/rstcheck/rstcheck
  rev: 'v6.1.2'
  hooks:
  - id: rstcheck
    additional_dependencies: [tomli]
    args: [-r, --config, ./pyproject.toml]

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.13.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

## Check for misspells in documentation files:
# - repo: https://github.com/codespell-project/codespell
#   rev: v2.2.5
#   hooks:
#   - id: codespell
